# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

formatting:
  Indentation:
    continuationIndentSize: 8
  ParameterListWrapping:
    active: false
  MaximumLineLength:
    maxLineLength: 200

exceptions:
  TooGenericExceptionCaught:
    active: false
  SwallowedException:
    ignoredExceptionTypes:
      - 'InterruptedException'
      - 'MalformedURLException'
      - 'NumberFormatException'
      - 'ParseException'
      - 'NoSuchFieldException'
      - 'InaccessibleObjectException'
      - 'SecurityException'

complexity:
  TooManyFunctions:
    active: false

style:
  MaxLineLength:
    maxLineLength: 200

