package org.github.olloginov.ideataskbrowser;

import org.github.olloginov.ideataskbrowser.model.TaskTreeModel;
import org.github.olloginov.ideataskbrowser.model.TaskTreeRenderer;

import javax.swing.*;
import javax.swing.tree.TreeNode;
import javax.swing.tree.TreePath;
import javax.swing.tree.TreeSelectionModel;
import java.awt.*;

public class TaskBrowserPanel {

    private JPanel root;
    private JSplitPane contentSplitter;
    private JTree tree;
    private JPanel preview;
    private JScrollPane treeScroll;

    private TaskTreeModel treeModel = new TaskTreeModel();

    public TaskBrowserPanel() {
        tree.setModel(treeModel);
        tree.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        tree.setCellRenderer(new TaskTreeRenderer());
    }

    public TaskTreeModel getModel() {
        return treeModel;
    }

    public TreeNode getSelectedNode() {
        TreePath selectionPath = tree.getSelectionPath();
        if (selectionPath == null) {
            return null;
        }
        return (TreeNode) selectionPath.getLastPathComponent();
    }

    public void setToolbar(JComponent component) {
        root.add(component, BorderLayout.WEST);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root = new JPanel();
        root.setLayout(new BorderLayout(0, 0));
        contentSplitter = new JSplitPane();
        contentSplitter.setDividerLocation(332);
        root.add(contentSplitter, BorderLayout.CENTER);
        preview = new JPanel();
        preview.setLayout(new BorderLayout(0, 0));
        contentSplitter.setRightComponent(preview);
        treeScroll = new JScrollPane();
        contentSplitter.setLeftComponent(treeScroll);
        tree = new JTree();
        tree.setRootVisible(false);
        tree.setShowsRootHandles(true);
        treeScroll.setViewportView(tree);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }
}
